config/routes.rb
Rails.application.routes.draw do
  get 'superheros/index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :posts do
  	resources :comments
  end

  root 'posts#index'
  get "/about", to: "pages#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }
	validates :body, presence: true
end

app/models/superhero.rb
class Superhero < ApplicationRecord
  has_many :superpowers
end

app/models/superpower.rb
class Superpower < ApplicationRecord
  belongs_to :superhero
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:name, :body))

		redirect_to post_path(@post)
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy

		redirect_to post_path(@post)
	end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about

	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order('created_at DESC')
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new(post_params)
		
		# if @post.save
		# redirect_to @post
		# else
		# render 'new'
		# end
# byebug
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { head :ok }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
	end	

	def show
		@post = Post.find(params[:id])
	end

	def edit
		@post = Post.find(params[:id])
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(params[:post].permit(:title, :body))
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to root_path
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController
  def index
    @superheros = Superhero.search(params[:search])
  end

  private

  def superhero_params
    params.require(:superhero).permit(:name, :super_name, :search)
  end
end

app/controllers/superpowers_controller.rb
class SuperpowersController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/superheros_helper.rb
module SuperherosHelper
end

app/helpers/superpowers_helper.rb
module SuperpowersHelper
end

app/views/comments/_comment.html.erb
<div class="comment clearfix">
	<div class="comment_content">
		<p class="comment_name"><strong><%= comment.name %></strong></p>
		<p class="comment_body"><%= comment.body %></p>
		<p class="comment_title"><%= time_ago_in_words(comment.created_at) %> Ago </p>
	</div>
	<% if user_signed_in? %>
		<p><%= link_to 'Delete', [comment.post, comment], method: :delete, class: 'button', data: { confirm: "Are you sure?"} %></p>
	<% end %>
</div>	

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<p>
		<%= f.label :name %><br/>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :body %><br/>
		<%= f.text_area :body %>
	</p><br/>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tumblr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://googleapis.com/css?family=Raleway:400,700", rel="stylesheet", type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<!-- jQuery library -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!-- Latest compiled JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
	<%#= favicon_link_tag 'favicon.ico' %>
	 <link href="/assets/favicon.ico" rel="shortcut icon" type="image/x-icon" />
  </head>

  <body>
  	<div id="sidebar">
  		<ul>
  			<li class="category"><%= link_to 'Tumblr', root_path %></li>
  			<li><%= link_to "Posts", root_path %></li>
  			<li><%= link_to "About", about_path %></li>
  		</ul>
      <% if !user_signed_in? %>
  	  	<p class="sign_in"><%= link_to "User Login", new_user_session_path %></p>
  	  <% end %>
    </div>

  	<div id="main_content">
  		<div id="header">
        <% if current_page?(root_path) %>
  			   <p>Post Feed</p>
        <% elsif current_page?(about_path) %>
           <p>My Site</p>
        <% else %>
           <%= link_to "Back to Post Feed", root_path %>
        <% end %>
        <% if user_signed_in? %> 
    			<div class="buttons">
    				<button class="button"><%= link_to "Make Post", new_post_path %></button>
    				<button class="button"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></button>
    			</div>
        <% end %>
  		</div>

  		<% flash.each do |name, msg| %>
  			<%= content_tag(:div, msg, class: "alert") %>
  		<% end %>
	    <%= yield %>
  	</div>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page_wrapper">
  <div id="profile_image">
  	<%= image_tag "profile.jpeg" %>
  </div>

  <div id="content">
  <h1>It's Mr. Stick Figure</h1>
  <p>I would like to share a story with you. This is a simple story of how your faith and your belief can make a difference in someone else's life without you even knowing it.

My story begins sadly as I lost someone I loved dearly to what I now call "The Beast." What I am referring to is suicide. The woman I loved was overcome with past emotions and events that, eventually, wound up taking her away from me.

For months, even years, I struggled with this as I had no idea about what depression was nor how it impacted your life so deeply. Now, I've discovered, it is not only a common affliction but also not easily treatable by today's medical community.

Becoming deeply depressed myself, and not taking good care of my health, I finally turned my life to God, The Son and The Holy Spirit. It was here, I eventually found solace in my world.

I began taking weekend trips to the shore where I would observe the sunrise and literally feel the glory of God as I watched the sun break the horizon; felt the wind from the sea filling me with the Holy Spirit; and the mist from the ocean caressing my face as if Jesus himself was calming my aching soul.</p>
  </div>
</div>

app/views/posts/_form.html.erb
	<%= form_for @post do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>		
		<% end %>
		<p>
			<%= f.label :title %><br/>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br/>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>

app/views/posts/edit.html.erb
<div id="page_wrapper">
	<h1>Edit Post</h1>
	<%= render 'form' %>
</div>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
	<div class="post_wrapper">
		<h2 class="title"><%= link_to post.title, post %></h2>
		<p class="body"><%= truncate(post.body, length:100) %></p>
		<p class="date"><%= time_ago_in_words(post.created_at) %></p>
	</div>
<% end %>

app/views/posts/new.html.erb
<div id="page_wrapper">
	<h1>Make something</h1>

	<%= form_for :post, url: posts_path do |f| %>
		<% if @post.errors.any? %>
			<div id="errors">
				<h2><%= pluralize(@post.errors.count, "error") %> stopped this post saving</h2>
				<ul>
					<% @post.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
			</div>		
		<% end %>
		<p>
			<%= f.label :title %><br/>
			<%= f.text_field :title %>
		</p>

		<p>
			<%= f.label :body %><br/>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit %>
		</p>
	<% end %>
</div>

app/views/posts/show.html.erb
<div class="post_content">
	<h1 class="title">
		<%= @post.title %>
	</h1>

	<p class="date">
		Submitted <%= time_ago_in_words(@post.created_at) %> ago 
		<% if user_signed_in? %>
			<%= link_to 'Edit', edit_post_path(@post) %> |
			<%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?'} %>	
		<% end %>
	</p>
	<p class="body">
		<%= @post.body %>
	</p>

	<div id="comments">
		<h2><%= @post.comments.count %> Comments</h2>
		<%= render @post.comments %>
		<h3>Join Discussion: </h3>
		<%= render 'comments/form' %>
	</div>
</div>

app/views/superheros/index.html.erb
<h1>All SuperHeros</h1>

<h4>Search by Superpower</h4>
  <%= form_tag(superhero_path, method: :get) do %>
    <%= text_field_tag(:search, params[:search]) %>
    <%= submit_tag ("Search") %>
  <% end %>

  <% @superheros.each do |superhero| %>
    <ul>
      <li><%= link_to superhero.name, superhero_path(superhero) %></li>
    </ul>
  <% end %>